### ISSUE TITLE
Claim xxx SDK

### ISSUE THREAD

**Issue by mtaro** [qlcchain/go-qlc#1017]
please update the QLC application at least once every 2 months to keep the application up-to-date and not slow when used.

My qlc address is:

qlc_1cipzrs3icdgseu8kenptj8bppgt83idrboou1irti5u1te9ajqon57qng9f

**Comment by ariesunny** [comment]
Hi @mtaro , got your message, do you mean the QLC-Tracker ? The desktop versions of QLC Chain wallet? https://github.com/qlcchain/QLCTracker/releases
