### ISSUE TITLE
Node not syncing: "No stream"

### ISSUE THREAD

**Issue by syalanuj** [qlcchain/go-qlc#1044]
### Description of the issue
I have started a node using docker compose, I am also able to connect through rpc endpoints and call them.
The problem is when the node is trying to snc the data. Error logs:
`{"level":"error","ts":"2020-03-30T11:05:07.356Z","logger":"sync","caller":"p2p/sync.go:81","msg":"no stream","stacktrace":"github.com/qlcchain/go-qlc/p2p.(*ServiceSync).Start\n\t/qlcchain/go-qlc/p2p/sync.go:81"}
`
I don't know waht is the root cause, I am running this on my local mac

### Issue-Type
- [x ] bug report
- [x ] question
- [x ] Documentation improvement

**Comment by wenchaopeng** [comment]
what version of docker image are you using

**Comment by wenchaopeng** [comment]
If there is no feedback, I will close this issue

**Comment by syalanuj** [comment]
Sorry for late reply, this happens when I build the latest docker image from the master branch.
The docker image from dockerhub works
