### ISSUE TITLE
Can I access settlement rpc endpoints

### ISSUE THREAD

**Issue by syalanuj** [qlcchain/go-qlc#1061]
**Is your feature request related to a problem? Please describe.**
Is there a way to access rpc settlement endpoints? I can see it only supports version 1.4 and above.
Can I build the master branch locally and access it?

I get a no stream error when I build it locally

**Comment by gythialy** [comment]
We're still developing the settlement feature, you have to deploy your own boot node and pov miner(s) to get it to work

**Comment by syalanuj** [comment]
I deployed the pov miner using docker compose up on the repo: https://github.com/qlcchain/qlc-miner
Started a boot node by changing the configuration in qlc.json "isBootNode": true

I still get the same error -
```
2020-04-09T17:53:46.802+0800    ERROR   sync    p2p/sync.go:81  no stream
github.com/qlcchain/go-qlc/p2p.(*ServiceSync).Start
        /Users/lynxanalytics/Desktop/lynx/repo/cylynx/qlcchain/go-qlc/p2p/sync.go:81
```

**Comment by wenchaopeng** [comment]
Currently our settlement network is running on the local area network，if you want to experience the functionality of settlement, you need to build an environment locally and deploy settlement contracts yourself.
you can use `--single` to run a node with dev mode,you can also use `--genesisSeed` to specify your own genesis account

**Comment by syalanuj** [comment]
Thanks a lot for your reply, I was more interested in the Settlements data, seems like it would be on your local network.
I will try to use when it is in production, please let me know when the new release is out

**Comment by wenchaopeng** [comment]
ok ,thanks for your support
