### ISSUE TITLE
bind port 9735 to ipv6

### ISSUE THREAD

**Issue by gythialy** [qlcchain/go-qlc#113]
### Description of the issue

run gqlc on linux, and it binds port 9735 to ipv6, are there any commands to force it to ip4 ? reported by  @ze-rix 

### Issue-Type
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS 
Ubuntu
* Go version 
* Release tag/commit of the code
v0.0.5

### Expected behavior
bind to ipv4

### Actual behavior
bind to ipv6

### Steps to reproduce

N/A

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )

![771549898069_ pic_hd](https://user-images.githubusercontent.com/773400/52607685-1b626380-2eb2-11e9-8a92-172d2b199af2.jpg)

**Comment by zengchen221** [comment]
@ze-rix when run gqlc,  does you use ipv4 to connect to server ? Is it possible to connect to the server？ or can you provide some detail info about issue ,thanks.
