### ISSUE TITLE
no response on newPending

### ISSUE THREAD

**Issue by realForbis** [qlcchain/go-qlc#1139]
### Description of the issue
Describe the issue you are experiencing.
I recieved only "create subscription" message but no response on newPending

### Issue-Type
- [x] bug report
- [ ] question
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS
Windows 10
* Go version
* Release tag/commit of the code

### Actual behavior
What is actually happening?
no response

**Comment by zengchen221** [comment]
thanks for your feedback，can you provide me more details, such as
- how do you call the interface,  like ``{"id":1,"method":"ledger_subscribe","params":["newPending","qlc_17mppebrj5kocjtr9i1wfxa1ooc9xqtgyqbemgr8wsjxck1xmcppp9abciaf"]}`` or not
- do you keep listening to the connection after "create subscription" successfully
- whether you use websocket 
- is the node local or qlc official 
- do you create send transation to the address，`newPending` can get response only if send block generated

**Comment by realForbis** [comment]
- call : {'id': 348, 'method': 'ledger_subscribe', 'params': ['newPending', 'qlc_3d69pzseenur455ppnxhg7wb16ibr6n345dxcn39n6u7fc9ju4336z8xxxxx']}
response : {"jsonrpc":"2.0","id":348,"result":"0xd5261b8e908f7df375df0c6719fa5d06"}
- Yes
-Yes, communication through websockets
- gqlc 1.3.5 mainnet
- Yes ("ledger_balanceChange", "ledger_newBlock", "pov_newBlock" are working and I'm getting responses but not for "newPending")

**Comment by zengchen221** [comment]
if you want get responses from "newPending" by `qlc_3d69pzseenur455ppnxhg7wb16ibr6n345dxcn39n6u7fc9ju4336z8xxxxx`,  must create send transaction to this address, or you can call `ledger_accountsPending` to check whether the pending is created.

**Comment by realForbis** [comment]
![recv](https://user-images.githubusercontent.com/37193612/84913816-369f3d80-b0bb-11ea-92d1-c69d1eefa0bb.png)
![recv_pubsub](https://user-images.githubusercontent.com/37193612/84913823-3737d400-b0bb-11ea-9d6d-e68e86bac57e.png)
![send](https://user-images.githubusercontent.com/37193612/84913825-37d06a80-b0bb-11ea-8f45-493feaedb93c.png)
![send_pubsub](https://user-images.githubusercontent.com/37193612/84913827-37d06a80-b0bb-11ea-9c64-e1c7a64f63cf.png)

**Comment by zengchen221** [comment]
this is really a bug, and has fixed on master branch.
