### ISSUE TITLE
qlc node 1.4 chain token info or gas token info mismatch

### ISSUE THREAD

**Issue by akefallonitis** [qlcchain/go-qlc#1186]
2020-07-10T12:32:00.227Z        INFO    chain   commands/root.go:170    Run node id: c0a269b04448f0fa884961198738a10a3c07837c39fe6e1276ce18c9030153bb
2020-07-10T12:32:00.228Z        INFO    chain   commands/root.go:173    run node SEED mode
2020-07-10T12:32:20.347Z        ERROR   chain   commands/root.go:240    chain token info or gas token info mismatch
github.com/qlcchain/go-qlc/cmd/server/commands.start
        /go-qlc/cmd/server/commands/root.go:240
github.com/qlcchain/go-qlc/cmd/server/commands.Execute.func1
        /go-qlc/cmd/server/commands/root.go:98
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/qlcchain/go-qlc/cmd/server/commands.Execute
        /go-qlc/cmd/server/commands/root.go:115
main.main
        /go-qlc/cmd/main.go:36
runtime.main
        /usr/local/go/src/runtime/proc.go:203
chain token info or gas token info mismatch

**Comment by wenchaopeng** [comment]
is the executable file you are running gqlc or gqlce？

**Comment by akefallonitis** [comment]
./gqlc  --seed xxxxxxx --configParams=rpc.rpcEnabled=true

**Comment by akefallonitis** [comment]
It was an update from 1.3.5 it started backup and then crashed

**Comment by wenchaopeng** [comment]
can you find out the file named qlc.json,and give me the genesis info,then I can help to see what went wrong

**Comment by akefallonitis** [comment]
I gusess you mean this ? 

`        "genesis": {
                "genesisBlocks": [
                        {
                                "chainToken": true,
                                "gasToken": false,
                                "mintage": {
                                        "type": "ContractSend",
                                        "token": "45dd217cd9ff89f7b64ceda4886cc68dde9dfa47a8a422d165e2ce6f9a834fad",
                                        "address": "qlc_3qjky1ptg9qkzm8iertdzrnx9btjbaea33snh1w4g395xqqczye4kgcfyfs1",
                                        "balance": "0",
                                        "vote": "0",
                                        "network": "0",
                                        "storage": "0",
                                        "oracle": "0",
                                        "previous": "0000000000000000000000000000000000000000000000000000000000000000",
                                        "link": "681bf5253c64672fc54c93d3b5b9a20d28965cb8f80ba70460ed3f99cb547bd5",
                                        "message": "0000000000000000000000000000000000000000000000000000000000000000",
                                        "data": "6TrdxEXdIXzZ/4n3tkztpIhsxo3enfpHqKQi0WXizm+ag0+tAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADVKa6ehgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhoG/UlPGRnL8VMk9O1uaINKJZcuPgLpwRg7T+Zy1R71QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADUUxDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1FMQwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                        "povHeight": 0,
                                        "timestamp": 1553990401,
                                        "extra": "0000000000000000000000000000000000000000000000000000000000000000",
                                        "representative": "qlc_1t1uynkmrs597z4ns6ymppwt65baksgdjy1dnw483ubzm97oayyo38ertg44",
                                        "work": "000000000048f5b9",
                                        "signature": "0d09a049ae11a005648b9ea9f4d7f2ce2fed985a9ec0b7009c87970b99c4de7b3c53c44768e6c9565babd627c83971bae8a32001f20f7acf888a80a0897f8409"
                                },
                                "genesis": {
                                        "type": "ContractReward",
                                        "token": "45dd217cd9ff89f7b64ceda4886cc68dde9dfa47a8a422d165e2ce6f9a834fad",
                                        "address": "qlc_1t1uynkmrs597z4ns6ymppwt65baksgdjy1dnw483ubzm97oayyo38ertg44",
                                        "balance": "60000000000000000",
                                        "vote": "0",
                                        "network": "0",
                                        "storage": "0",
                                        "oracle": "0",
                                        "previous": "0000000000000000000000000000000000000000000000000000000000000000",
                                        "link": "c0d330096ec4ab6ccf5481e06cc54e74b14f534e99e38df486f47d1123cbd1ae",
                                        "message": "0000000000000000000000000000000000000000000000000000000000000000",
                                        "data": "Rd0hfNn/ife2TO2kiGzGjd6d+keopCLRZeLOb5qDT60AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANUprp6GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGgb9SU8ZGcvxUyT07W5og0olly4+AunBGDtP5nLVHvVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgb9SU8ZGcvxUyT07W5og0olly4+AunBGDtP5nLVHvVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANRTEMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADUUxDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
                                        "povHeight": 0,
                                        "timestamp": 1553990410,
                                        "extra": "0000000000000000000000000000000000000000000000000000000000000000",
                                        "representative": "qlc_1t1uynkmrs597z4ns6ymppwt65baksgdjy1dnw483ubzm97oayyo38ertg44",
                                        "work": "000000000048f5b9",
                                        "signature": "76fb8d1e5decf145616ee1b5713ad81b5792cadcc054a9d999d5acf026924e8ccb23f96994cf8a056b5e0a74706e4ccb7314dc989b1fccbcd88c024bb31c6b0d"
                                }
                        },
                        {
                                "chainToken": false,
                                "gasToken": true,
                                "mintage": {
                                        "type": "ContractSend",
                                        "token": "ea842234e4dc5b17c33b35f99b5b86111a3af0bd8e4a8822602b866711de6d81",
                                        "address": "qlc_3qjky1ptg9qkzm8iertdzrnx9btjbaea33snh1w4g395xqqczye4kgcfyfs1",
                                        "balance": "0",
                                        "vote": "0",
                                        "network": "0",
                                        "storage": "0",
                                        "oracle": "0",
                                        "previous": "0000000000000000000000000000000000000000000000000000000000000000",
                                        "link": "dd803c6bdb9878a35a3e447e4d88b8df4f65eecd35d7506157750ea46e2c6133",
                                        "message": "0000000000000000000000000000000000000000000000000000000000000000",
                                        "data": "6TrdxOqEIjTk3FsXwzs1+ZtbhhEaOvC9jkqIImArhmcR3m2BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjhvJvwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjdgDxr25h4o1o+RH5NiLjfT2XuzTXXUGFXdQ6kbixhMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEUUdBUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFFHQVMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                        "povHeight": 0,
                                        "timestamp": 1553990401,
                                        "extra": "0000000000000000000000000000000000000000000000000000000000000000",
                                        "representative": "qlc_1t1uynkmrs597z4ns6ymppwt65baksgdjy1dnw483ubzm97oayyo38ertg44",
                                        "work": "000000000048f5b9",
                                        "signature": "175df7302eb8d830da4d86047819b4680f5a3c425ed8bc6593a4dd724c847aceac68b63bebfbde94d368b4e24182dd503f05ac474d231c6a17455fa131f0d10f"
                                },
                                "genesis": {
                                        "type": "ContractReward",
                                        "token": "ea842234e4dc5b17c33b35f99b5b86111a3af0bd8e4a8822602b866711de6d81",
                                        "address": "qlc_3qe19joxq85rnff5wj5ybp6djqtheqqetfgqc3iogxagnjq4rrbmbp1ews7d",
                                        "balance": "10000000000000000",
                                        "vote": "0",
                                        "network": "0",
                                        "storage": "0",
                                        "oracle": "0",
                                        "previous": "0000000000000000000000000000000000000000000000000000000000000000",
                                        "link": "bdac41b3ff7ac35aee3028d60eabeb9578ea6f7bd148d611133a3b26dfa6a9be",
                                        "message": "0000000000000000000000000000000000000000000000000000000000000000",
                                        "data": "6oQiNOTcWxfDOzX5m1uGERo68L2OSogiYCuGZxHebYEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACOG8m/BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACN2APGvbmHijWj5Efk2IuN9PZe7NNddQYVd1DqRuLGEzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN2APGvbmHijWj5Efk2IuN9PZe7NNddQYVd1DqRuLGEzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRR0FTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEUUdBUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
                                        "povHeight": 0,
                                        "timestamp": 1553990410,
                                        "extra": "0000000000000000000000000000000000000000000000000000000000000000",
                                        "representative": "qlc_1t1uynkmrs597z4ns6ymppwt65baksgdjy1dnw483ubzm97oayyo38ertg44",
                                        "work": "000000000048f5b9",
                                        "signature": "4e605d4ccfe3f061c1139eecec25b1129dbe491b12c42eb34e3febadc40971ff42e7240f9f42432591172cc5a91292406fe7b3115c757945e9c8848b83836001"
                                }
                        }
                ]
`

**Comment by wenchaopeng** [comment]
yes.this is what I want,this genesis info is correct，then only one possibility is that your ledger is wrong，have you ever run a testnet version？

**Comment by wenchaopeng** [comment]
or have you operated the ledger folder?

**Comment by akefallonitis** [comment]
Nope and Nope i was running my node as always for several months now

Since this morning that i download the new version of qlc and replase the old binary and try to start it:

./gqlc --seed xxxxxxx --configParams=rpc.rpcEnabled=true

**Comment by wenchaopeng** [comment]
how much disk space does your ledger folder occupy？

**Comment by akefallonitis** [comment]
![image](https://user-images.githubusercontent.com/24274227/87164156-15ec9100-c2d1-11ea-9912-628ea7bc8b98.png)

**Comment by wenchaopeng** [comment]
It seems that your local ledger is not the correct size, and you need to wait for the official upgrade the Bootstrap node to v1.4.0 and then you can upgrade the local node，

**Comment by wenchaopeng** [comment]
Did you create the ledger16.bakup file manually？

**Comment by akefallonitis** [comment]
yes but now how can i roll back ? if i try to start it with 1.3.5 i am getting another error

No the backup run when i trying the new version automatically i suppose

So what you suggest doing to run the 1.3.5 version ?

**Comment by wenchaopeng** [comment]
I guess your local ledger is damaged, so you need to resynchronize the ledger, delete the .gqlcchain folder, back up before deleting, and then re-run v1.3.5

**Comment by wenchaopeng** [comment]
did you manually close the process before the ledger upgrade was completed?

**Comment by wenchaopeng** [comment]
I reproduced your situation in my local environment，this is because the process is closed before the ledger upgrade is completed

**Comment by akefallonitis** [comment]
Nope i did no close anything it just crashed even running with `screen` i roll back and now my node is up and running
