### ISSUE TITLE
ledger_transactionsCount returning number of blocks

### ISSUE THREAD

**Issue by realForbis** [qlcchain/go-qlc#1200]
### Issue-Type
- [x] bug report
- [ ] question
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Expected behavior
returning number of TX's

### Actual behavior
returning number of blocks(count, unchecked)... same call as "ledger_blocksCount"

### Steps to reproduce
{
  "jsonrpc": "2.0",
  "id":3,
  "method":"ledger_transactionsCount"
}

**Comment by zengchen221** [comment]
i think it is not a bug,   the results returned by these two interfaces are the same at present
