### ISSUE TITLE
integration test for version 1.4.2

### ISSUE THREAD

**Issue by zengchen221** [qlcchain/go-qlc#1289]
- integration test for version 1.4.2

**Comment by ioannistsil** [comment]
are you planing to release new version of go-qlc?

**Comment by ioannistsil** [comment]
why you are not closing this issue?

**Comment by gythialy** [comment]
Thanks for your attention, we will close it in this weekend.

**Comment by gythialy** [comment]
[v1.4.2-beta1](https://github.com/qlcchain/go-qlc/releases/tag/v1.4.2-beta1) has been released
