### ISSUE TITLE
hi what is wrong

### ISSUE THREAD

**Issue by mstc-xqp** [qlcchain/go-qlc#1389]
![image](https://user-images.githubusercontent.com/19384581/117924427-50c3b900-b328-11eb-8ca4-9e3f713e018a.png)

**Comment by zengchen221** [comment]
hi, what's your node version, please use the latest version v1.5.1

**Comment by mstc-xqp** [comment]
> hi, what's your node version, please use the latest version v1.5.1

i use. docker version

**Comment by zengchen221** [comment]
```
curl --request POST \
  --url http://127.0.0.1:9735/ \
  --header 'Content-Type: application/json' \
  --data '{
	"jsonrpc": "2.0",
	"id": 18,
	"method": "debug_nodeStatus"
}'
```
please execute this command and paste the result

**Comment by mstc-xqp** [comment]
> ```
> curl --request POST \
>   --url http://127.0.0.1:9735/ \
>   --header 'Content-Type: application/json' \
>   --data '{
> 	"jsonrpc": "2.0",
> 	"id": 18,
> 	"method": "debug_nodeStatus"
> }'
> ```
> 
> please execute this command and paste the result

你好。我是直接运行docker这个命令的

docker container run -d --name go-qlc \
--restart always \
-p 19734:19734 \
-p 19735:19735 \
-p 19736:19736 \
-v /root/.gqlcchain:/root/.gqlcchain \
qlcchain/go-qlc:v1.0.1

**Comment by mstc-xqp** [comment]
![Uploading image.png…]()

**Comment by zengchen221** [comment]
> 你好。我是直接运行docker这个命令的
> 
> docker container run -d --name go-qlc
> --restart always
> -p 19734:19734
> -p 19735:19735
> -p 19736:19736
> -v /root/.gqlcchain:/root/.gqlcchain
> qlcchain/go-qlc:v1.0.1


the version and ports are not correct, should like this:
```
docker container run -d --name go-qlc-v1.5.1 \
-p 9734:9734 \
-p 127.0.0.1:9735:9735 \
-p 127.0.0.1:9736:9736 \
qlcchain/go-qlc:v1.5.1  --configParams=rpc.rpcEnabled=true
```

**Comment by mstc-xqp** [comment]
![image](https://user-images.githubusercontent.com/19384581/117936734-ca16d800-b337-11eb-87a9-c882f63719a0.png)


> > 你好。我是直接运行docker这个命令的
> > docker container run -d --name go-qlc
> > --restart always
> > -p 19734:19734
> > -p 19735:19735
> > -p 19736:19736
> > -v /root/.gqlcchain:/root/.gqlcchain
> > qlcchain/go-qlc:v1.0.1
> 
> the version and ports are not correct, should like this:
> 
> ```
> docker container run -d --name go-qlc-v1.5.1 \
> -p 9734:9734 \
> -p 127.0.0.1:9735:9735 \
> -p 127.0.0.1:9736:9736 \
> qlcchain/go-qlc:v1.5.1  --configParams=rpc.rpcEnabled=true
> ```

**Comment by mstc-xqp** [comment]
docker stop 390c649afc18
390c649afc18
infosec@InfoSecdeMBP ~ % curl --request POST \   
  --url http://127.0.0.1:9735/ \
  --header 'Content-Type: application/json' \
  --data '{
        "jsonrpc": "2.0",
        "id": 18,
        "method": "debug_nodeStatus"
}'
{"jsonrpc":"2.0","id":18,"result":{"buildTime":"2021-04-25T08:16:08Z+0000","gitRev":"6380e20","version":"v1.5.1","mode":"MainNet","ledgerStatus":{"blockCount":4,"unCheckedBlockCount":1519},"netStatus":{"peerId":"QmWu3mvCeYdfjJwKsB6t9gFwVS1U8HcMXRJmL88zMUXPHh","connectedPeers":[{"peerid":"QmQYgG7xUCC9FEKX1SCy2ddbcQGBacTMXd2n2Z2Ym92CkP","address":"/ip4/78.46.223.248/tcp/9734","version":"1.5.0-2629e7f","rtt":0.236756,"lastUpdateTime":"2021-05-12T07:35:15Z"},{"peerid":"QmfPEp8Hgs3fmuxmY791D34JcwMsKuYtBBVhkY3dat7Kyy","address":"/ip4/178.63.50.78/tcp/9734","version":"v1.5.0-2629e7f","rtt":0.2259185,"lastUpdateTime":"2021-05-12T07:35:15Z"},{"peerid":"QmU4zkzkZfnt4eTrbAPUnRyBdXUmZ33K3B5vAt5p8SBicD","address":"/ip4/50.116.1.188/tcp/9734","version":"1.4.1-6c2c460","rtt":0.1705988,"lastUpdateTime":"2021-05-12T07:35:15Z"},{"peerid":"QmYppqRivHYHmWZmchmJgAnjocdecE6TBkZjiqWiAWFird","address":"/ip4/47.244.138.61/tcp/9734","version":"v1.5.1-6380e20","rtt":0.0141201,"lastUpdateTime":"2021-05-12T07:35:15Z"},{"peerid":"QmQ4cZL8wV1GgT2r7bQ1qBawwgMGyxGivYDaSfiTzdXr4U","address":"/ip4/47.103.40.20/tcp/9734","version":"v1.5.1-6380e20","rtt":0.0312973,"lastUpdateTime":"2021-05-12T07:35:15Z"},{"peerid":"QmTLpST1Kr8mJMi68E25dSArzXBNAQRa8aoi4qdzfLVpN3","address":"/ip4/47.75.145.146/tcp/9734","version":"v1.5.1-6380e20","rtt":0.0159466,"lastUpdateTime":"2021-05-12T07:35:15Z"},{"peerid":"QmPhdXf4yrZ2ftAAWSJBAMfCkH23xeJGTx7sRM6CqxU6gJ","address":"/ip4/47.75.71.52/tcp/9734","version":"v1.5.1-6380e20","rtt":0.0136488,"lastUpdateTime":"2021-05-12T07:35:15Z"},{"peerid":"QmcJZ5JSkg5FTNys99fd4JBcescBXTMQsmerJgUVkCkd75","address":"/ip4/47.244.109.23/tcp/9734","version":"v1.5.1-6380e20","rtt":0.0174201,"lastUpdateTime":"2021-05-12T07:35:15Z"},{"peerid":"QmQHKuusXiPKDU18MtSbJgzejqetPbczLmg9YL98FmL5rE","address":"/ip4/86.142.2.58/tcp/9734","version":"v1.4.2-cf3587a","rtt":0.2364577,"lastUpdateTime":"2021-05-12T07:35:15Z"}],"onlineRepresentatives":null,"onlineRepresentativeInfos":{"Reps":null,"ValidVotes":"0","ValidVotesPercent":""}},"povStatus":{"povEnabled":true,"syncState":1,"syncStateStr":"Synchronizing","povLedgerStats":{"povBlockCount":2,"povBestCount":2,"povAllTxCount":6,"povCbTxCount":2,"povStateTxCount":4,"stateBlockCount":4},"povMiningInfo":{"syncState":1,"syncStateStr":"Synchronizing","currentBlockHeight":1,"currentBlockHash":"1e29ee3538c21ef1bb95f5c4dc877c5b1e3a29683e8dccb49b2ede46419fcef1","currentBlockSize":730,"currentBlockTx":5,"currentBlockAlgo":256,"pooledTx":0,"difficulty":1.000015259254738,"hashInfo":{"chainHashPS":2026,"sha256dHashPS":0,"scryptHashPS":2026,"x11HashPS":0},"minerAddr":"","algoName":"","algoEfficiency":12984,"cpuMining":false},"latestHeader":{"basHdr":{"version":536871168,"previous":"92bafc7a0079ffd173c1228bbeb2bf95285df578bf1c7a9b5881b1a500000000","merkleRoot":"87f48894bf269de26a7dd019661ad5ea9ab383c0c4aa8c3ab25ce93595ee62f0","timestamp":1577710303,"bits":506640333,"nonce":2693071104,"hash":"1e29ee3538c21ef1bb95f5c4dc877c5b1e3a29683e8dccb49b2ede46419fcef1","height":1},"auxHdr":null,"cbtx":{"version":1,"txIns":[{"prevTxHash":"0000000000000000000000000000000000000000000000000000000000000000","prevTxIdx":4294967295,"extra":"5104dff2095e2f514c4320536f6c6f20506f6f6c2f840086cf0000000000000000","sequence":4294967295}],"txOuts":[{"value":"342465753","address":"qlc_1dkxwx67bhha1wrwa337s9gscjo1wqb3ru5riuhhkh7ba14fw19bepj4x8fb"},{"value":"228310502","address":"qlc_111111111111111111111111111111111111111111111111111ommygmckp"}],"stateHash":"11a186488fd5dfae3b830228e5903c5f2f99ebb88d1776be8a8ef65277901baa","txNum":5,"hash":"331eecf8214c2eb2d68eef0979b3e5f18d7d7bc68ef08c3f16321ab11a916794"},"algoName":"SCRYPT","algoEfficiency":12984,"normBits":486604798,"normDifficulty":1.000015259254738,"algoDifficulty":0.00007701787466232713}}}}
infosec@InfoSecdeMBP ~ %

**Comment by mstc-xqp** [comment]
这应该是运行不成功吧 我没有进入docker 容器里面。运行不了命令

**Comment by mstc-xqp** [comment]
您好 请问你们有新的文档吗

**Comment by zengchen221** [comment]
No need to enter the container，just start the container with the command, 
```
docker container run -d --name go-qlc-v1.5.1 \
-p 9734:9734 \
-p 9735:9735 \
-p 9736:9736 \
-v {your-local-path}:/qlcchain/.gqlcchain \
qlcchain/go-qlc:v1.5.1  --configParams=rpc.rpcEnabled=true
```

then you can access the node service. 

```
curl --request POST \
  --url http://127.0.0.1:9735/ \
  --header 'Content-Type: application/json' \
  --data '{
	"jsonrpc": "2.0",
	"id": 18,
	"method": "debug_nodeStatus"
}'
```
document,  https://docs.qlcchain.online/

**Comment by mstc-xqp** [comment]
> https://docs.qlcchain.online/
docker 那个命令 改了端口  是可以新增不同节点吗

你好。acess 之后能运行其他什么命令吗

**Comment by mstc-xqp** [comment]
> > https://docs.qlcchain.online/
> > docker 那个命令 改了端口  是可以新增不同节点吗
> 
> 你好。acess 之后能运行其他什么命令吗

感谢我跟觉rpc 已经跑起来了

**Comment by mstc-xqp** [comment]
![image](https://user-images.githubusercontent.com/19384581/117952662-f4709180-b347-11eb-9e76-e94b6d92a4d0.png)
他有些是没返回结果 
请问 这个docker 一开始先新建了19个节点吗 自带的

**Comment by zengchen221** [comment]
no result returned because there is no data that meets the parameters
one docker container only create one local node

**Comment by mstc-xqp** [comment]
![image](https://user-images.githubusercontent.com/19384581/117954808-f76c8180-b349-11eb-84db-171bec5166a7.png)
这个地址是你们官方通用的吗

**Comment by mstc-xqp** [comment]
> no result returned because there is no data that meets the parameters
> one docker container only create one local node
Thank you very much.   

If I change the port   like


docker container run -d --name go-qlc-v1.5.1 \
-p 2734:2734 \
-p 2735:2735 \
-p 2736:2736 \
-v {your-local-path}:/qlcchain/.gqlcchain \
qlcchain/go-qlc:v1.5.1  --configParams=rpc.rpcEnabled=true


will it create a new node?

**Comment by zengchen221** [comment]
cannot change the container inner port, you can change the local port and mount path to create a node

```
docker container run -d --name go-qlc-newname \
-p 29734:9734 \
-p 29735:9735 \
-p 29736:9736 \
-v {new-path}:/qlcchain/.gqlcchain \
qlcchain/go-qlc:v1.5.1  --configParams=rpc.rpcEnabled=true
```

**Comment by mstc-xqp** [comment]
![image](https://user-images.githubusercontent.com/19384581/118092955-55a76c00-b3ff-11eb-9a75-f1d7e475de43.png)
请问整个功能是怎么跑通的呢？计费，交易，节点间传输数据

**Comment by mstc-xqp** [comment]
请问整个功能是怎么跑通的呢？计费，交易，节点间传输数据
![image](https://user-images.githubusercontent.com/19384581/118100090-a5d6fc00-b408-11eb-9e40-42df5f3606d6.png)

**Comment by mstc-xqp** [comment]
![image](https://user-images.githubusercontent.com/19384581/118158287-2835df00-b44e-11eb-9891-191ade42bcbb.png)

it doest not run

我开了两个docker 
ocker container run -d --name go-qlc-v1.5.1v2 \
-p 29734:9734 \
-p 127.0.0.1:29735:9735 \
-p 127.0.0.1:29736:9736 \
qlcchain/go-qlc:v1.5.1  --configParams=rpc.rpcEnabled=true

**Comment by zengchen221** [comment]
the rpc interface parameters in the document are just example,  you should use the actual parameters

**Comment by mstc-xqp** [comment]
should i buy a basestions and download a qwallet?



---Original---
From: ***@***.***&gt;
Date: Mon, May 17, 2021 09:40 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [qlcchain/go-qlc] hi what is wrong (#1389)




 
the rpc interface parameters in the document are just example,  you should use the actual parameters

**Comment by mstc-xqp** [comment]
> the rpc interface parameters in the document are just example, you should use the actual parameters
Many thanks!
should i buy a basestions and download a qwallet?

**Comment by zengchen221** [comment]
you can download a Q-Wallet
