### ISSUE TITLE
gqlcc CLI not found

### ISSUE THREAD

**Issue by lonnietc** [qlcchain/go-qlc#1433]
I have been testing the latest QLC 1.5.1 from the releases but the "gqlcc" CLI application is not available as described in the documentation

https://github.com/qlcchain/go-qlc/wiki/CLI-Introduction

**Comment by lonnietc** [comment]
Hello,

I have been researching your past versions and it seems that the last version that has separate server (gqlc) and client (gqlcc) applications generated was v1.2.7.1.

Beginning with v1.3.0, it seems that you you merged the 2 applications into a single application, but I cannot see that the gqlcc client functionality is present even in the latest  v1.5.1 build.

The online documentation has not been updated to explain the use of the client side operations for v1.5.1.

Can you please help as I am trying to setup a small private Testnet with some server nodes and then would like to connect via a QLC client to test out some operations?

Please help with the documentation to clarify this.

**Comment by realForbis** [comment]
with current build (v1.5.1) there are 2 executable files. first one is gqlc (mainnet) and the second one gqlce (testnet) for flags use -h or --help.
if you want to work with node, docs with all rpc calls is here : https://docs.qlcchain.online/api/rpc/

**Comment by lonnietc** [comment]
@realForbis  Hello and thanks for responding to my inquiry.

I was able to already work with the server node side commands that you mentioned, but was trying to figure out how to use the Client CLI documents 

https://docs.qlcchain.online/tutorial/node/cli.html#client

These do not seem to be accurate any more since the qglcc client is not generated.

In reviewing the source code, it seems that the v1.5.1 has merged the "gqlc" server and "gqlcc" client into a single application via one main.go source to shell of either a server or client based upon the command line switches.  Personally, I really like the idea of having 2 separate applications instead of a single one.

The other problem that I am having and reported on was in trying to start up from the command line in that the libp2p library is reporting a private network protection error.

Actually, what I would really like is some help on how to set up my own separate private testnet so that I can do some development and testing but there is really no guidance that I have found so far and have not been able to get much support from the go-qlc github site.

Would you be willing to discuss some of these things with me?   If so, then maybe I can invite you to my slack channel to take it offline from the  github issue channel a bit.

**Comment by lonnietc** [comment]
@realForbis If you would like to send me an email to : Lonnie@outstep.com then maybe we can chat a little more on some questions that I have about the QLC chain as I would enjoy that very much.
