### ISSUE TITLE
Is there no support for go-qlc ???

### ISSUE THREAD

**Issue by lonnietc** [qlcchain/go-qlc#1434]
Hi,

I am trying to get familiar with the go-qlc code base.

Why is there no support?

**Comment by joekah** [comment]
There is no support coz the team is no longer together. Even their token got delisted by some exchanges.

**Comment by lonnietc** [comment]
Wow, it seems that QLC had good potential and I initially wanted to build a solid token from its base, but now their project may have fallen apart.

Sorry to see as I tried to very hard to locate some developers and get even a little support to work together with them, but had not luck.
