### ISSUE TITLE
receive block will not be generated when the target node is broken down after adding the send block to the ledger

### ISSUE THREAD

**Issue by lc3091** [qlcchain/go-qlc#153]
### Description of the issue
receive block will not be generated when the target node is broken down after adding the send block to the ledger

### Issue-Type
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* WINDOWS
* Go 1.11.5
* v0.0.5

### Expected behavior
reveive block can be generated normally

### Actual behavior
reveive block can not be generated

### Steps to reproduce
1. There's a very low probability to meet this, but it will happen.

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
file  :  ledger_processor.go
func  :  processStateBlock
![image](https://user-images.githubusercontent.com/9348530/53473951-c2e0b800-3aa6-11e9-88b5-8a0dde2cd758.png)

**Comment by zengchen221** [comment]
`processStateBlock` executes in a transaction , if error occurs after adding the send block to the ledger, the whole process will rollback.
