### ISSUE TITLE
Rewards to the best solution for this challenge

### ISSUE THREAD

**Issue by txdzhang** [qlcchain/go-qlc#293]
### QLC Hacker Challenge with Rewards 

This is a real business and technology requirement: 

if one of the largest mobile carriers in the world submits a packet with 15mn destination numbers of messages at the same time to QLC mainnet for the billing process, what's your idea to process such a large pack in the trusted environment, and to guarantee that no number is lost and all sent status is checked? Rewards prepared for the best solution.

Leave your proposal or questions in the comment and we will reward the best solution with QLCs. 

Looking forward!

**Comment by MrLennon** [comment]
The package of 15mn destination numbers could be split up in 1mn packages and handled by multiple (mainnet) nodes ?

**Comment by realForbis** [comment]
I think it depend on how many network confirmation they need and from how many nodes, how many data you can store into “1 block” and as i know QLC chain is feesless but i know they will have sms billing service (SC) on QLC chain so they will pay fees but fee price must be same on the entire package of TX, because increase of fee price can lead to spaming network.

**Comment by mrderrik** [comment]
Split packet up into equal portions according to number of nodes, then split packets again to minimum size needed to ensure safe delivery

**Comment by realForbis** [comment]
> Split packet up into equal portions according to number of nodes, then split packets again to minimum size needed to ensure safe delivery

I think this will lead to centralization, there will be few nodes at the beginning

**Comment by mrderrik** [comment]
> I think this will lead to centralization, there will be few nodes at the beginning

I don't understand something then....  This causes all nodes to participate equally, The number of nodes causes centralization, not how you distribute the packets?  

Another solution is to send packet to node performing least amount of work, and that node delegates portion of workload to next node in lone with least workload?

**Comment by realForbis** [comment]
What about to use some compression algorithm like LZ77, 
![image](https://user-images.githubusercontent.com/37193612/56676466-a6d05000-66be-11e9-86de-7a2be4366171.png)
Percentage ratio is just an example,

**Comment by xiaoyux** [comment]
intresting.Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [qlcchain/go-qlc] Rewards to the best solution for this challenge (#293)From: Forbis To: qlcchain/go-qlc CC: Subscribed What about to use some compression algorithm like LZ77,

Percentage ratio is just an example,

**Comment by realForbis** [comment]
> What about to use some compression algorithm like LZ77,
> ![image](https://user-images.githubusercontent.com/37193612/56676466-a6d05000-66be-11e9-86de-7a2be4366171.png)
> Percentage ratio is just an example,

![image](https://user-images.githubusercontent.com/37193612/56685111-7219c400-66d1-11e9-8608-de74f2cd9257.png)

**Comment by magicalponny** [comment]
Few questions:
1. Could you please define what do you mean by transactions being sent at the same time? You mean 15 million messages in one second or what?
2. Are these messages sent by the carrier being sent from the same source or many different sources and how does that map to your block-lattice accounts structure? One number one account?
3. From the Nano whitepaper it says that they achieved max 10k transactions per second on SSD commodity hardware and the bottleneck was mainly IO which assuming you're based on similar architecture would give you 15M/10k = 25min time to write all that down. Is that correct?
4. Guarantee of no number being lost... is your network send based on a reliable multicast protocol? Or you do some kind of unreliable multicast with retries?

**Comment by realForbis** [comment]
> Few questions:
> 
> 1. Could you please define what do you mean by transactions being sent at the same time? You mean 15 million messages in one second or what?
> 2. Are these messages sent by the carrier being sent from the same source or many different sources and how does that map to your block-lattice accounts structure? One number one account?
> 3. From the Nano whitepaper it says that they achieved max 10k transactions per second on SSD commodity hardware and the bottleneck was mainly IO which assuming you're based on similar architecture would give you 15M/10k = 25min time to write all that down. Is that correct?
> 4. Guarantee of no number being lost... is your network send based on a reliable multicast protocol? Or you do some kind of unreliable multicast with retries?


So if I understand correctly the best solution is to do it offchain.

**Comment by realForbis** [comment]
opening mulltisignature channel between them

**Comment by mrderrik** [comment]
I suppose we need to know if the packet can be split, how easy is it to do that, does it have to be submitted all at once, what is the maximum size or maximum number of transactions that can be handled at once (does each individual transaction have to be processed individually, if so do they have to all be free to do this or part of a group) How long do you have/need to process this group of transactions?

**Comment by ariesunny** [comment]
> I suppose we need to know if the packet can be split, how easy is it to do that, does it have to be submitted all at once, what is the maximum size or maximum number of transactions that can be handled at once (does each individual transaction have to be processed individually, if so do they have to all be free to do this or part of a group) How long do you have/need to process this group of transactions?

Yes, the packet can be split as one message number one transaction, For such great numbers, it is hardly to be submitted at once, it will help that spliting the whole traffic to several nodes to process parallelly. It is challage that 

> > What about to use some compression algorithm like LZ77,
> > ![image](https://user-images.githubusercontent.com/37193612/56676466-a6d05000-66be-11e9-86de-7a2be4366171.png)
> > Percentage ratio is just an example,
> 
> ![image](https://user-images.githubusercontent.com/37193612/56685111-7219c400-66d1-11e9-8608-de74f2cd9257.png)

Hey @realForbis ,What's the "N" here? Is it a node of the Chain？

**Comment by realForbis** [comment]
> > > What about to use some compression algorithm like LZ77,
> > > ![image](https://user-images.githubusercontent.com/37193612/56676466-a6d05000-66be-11e9-86de-7a2be4366171.png)
> > > Percentage ratio is just an example,
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/37193612/56685111-7219c400-66d1-11e9-8608-de74f2cd9257.png)
> 
> Hey @realForbis ,What's the "N" here? Is it a node of the Chain？

Yes
