### ISSUE TITLE
add config for genesis block

### ISSUE THREAD

**Issue by wenchaopeng** [qlcchain/go-qlc#311]
### Description of the issue
Describe the issue you are experiencing.

_Please put an `x` against the checkboxes._  

### Issue-Type
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS
* Go version
* Release tag/commit of the code

### Expected behavior
What should happen?

### Actual behavior
What is actually happening?

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by ioannistsil** [comment]
when genesis block will be available for qlc chain ?

**Comment by wenchaopeng** [comment]
done
