### ISSUE TITLE
Stability test of QLC Chain node on Confidant Device

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/go-qlc#340]
### Description of the issue
Verify the stability of runing a QLC Chain node on Confidant Device

**Comment by lc3091** [comment]
# Confidant上运行QLC Chain节点测试报告

- 初始状态

  ![init](https://user-images.githubusercontent.com/9348530/58317390-414fba80-7e48-11e9-962e-70b8e53e3326.png)

  初始启动后节点占用内存以及cpu资源都比较低

- 同步状态

  ![syncblock](https://user-images.githubusercontent.com/9348530/58317533-88d64680-7e48-11e9-8901-86a6774f9439.png)

  ​同步57898个块需要5到6个小时

  ![synnornal](https://user-images.githubusercontent.com/9348530/58317548-91c71800-7e48-11e9-809a-0068994f623c.png)

  同步时内存占用会比较大，最高会到800多m，cpu最大可以占到160%左右。

- 运行状态

  ![running](https://user-images.githubusercontent.com/9348530/58317498-722fef80-7e48-11e9-9ad8-8f5b2c10a8a5.png)

  块同步完成后，内存占用200多m，不影响设备的正常使用

- pow计算时间

  ![pow](https://user-images.githubusercontent.com/9348530/58317472-617f7980-7e48-11e9-9e33-8c692b2e0d3d.png)

  发送3个交易，块生成时间分别为28s，22s，49s，pow的时间都比较久。
