### ISSUE TITLE
running qlcchain on confidant will use too much memory

### ISSUE THREAD

**Issue by lc3091** [qlcchain/go-qlc#352]
### Description of the issue
running qlcchain on confidant will use too much memory

**Comment by ariesunny** [comment]
Detail info:
Memory occupied:
![image](https://user-images.githubusercontent.com/30827440/58170677-a54a7580-7cc6-11e9-8d14-1be008105e30.png)
 
Status screenshot:
![image](https://user-images.githubusercontent.com/30827440/58170750-e478c680-7cc6-11e9-8ffe-53717c05c7bf.png)
