### ISSUE TITLE
How to get the token ID when doing nep5_mintageWithdraw

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/go-qlc#382]
### Description of the issue
User will do the nep5_mintageWithdraw in "My Staking" page, it seems there is no easy way to to map the token id from the pledge info list.

### Issue-Type
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

**Comment by ariesunny** [comment]
Is it necessary of the wallet to provide the token id as there is neo txid in the request of nep5_mintageWithdraw .

**Comment by ariesunny** [comment]
BTW, wallet could not provide the unlockid as the unlock has not happened on NEO before call this method.
![image](https://user-images.githubusercontent.com/30827440/58566830-e06b1c80-8263-11e9-81a1-582b03a45a93.png)

**Comment by zengchen221** [comment]
no need to modify
