### ISSUE TITLE
Optimization for QLC Chain node running on Confidant Station

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/go-qlc#408]
### Description of the issue
1, Optimization of p2p sync when boot up
2, Optimization of memory occupied when running

### Issue-Type
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [ ] This issue has not been reported earlier.

Make sure QLC Chain node could be running on Confidant station stablely.

**Comment by lc3091** [comment]
move all special configuration for Confidant to one file and add a build tag for Confidant
