### ISSUE TITLE
Week #28 goals -- A good start of Q3 mission

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/go-qlc#443]
Integrating test of V1.2.3 @pwc5232759 @gythialy @zengchen221 @wenyuangui @lc3091 @ariesunny 
#444 integration testing v1.2.3

Service refractor @gythialy 
#442 refine service interface 

POV @wenyuangui 
#418 modify & test PoV miner reward contract 
#446 refactoring pov consensus module
#447 add some pov unit testcase

Confidant @lc3091 
#434 Add a build tag for Confidant 

Consensus 
#310 add block cache after basic check @pwc5232759 
#445 Feasibility research of adding the state block height @lc3091 

Ledger @zengchen221 
#433 Don't save contract related data if the block has not reached a consensus
#398 fix transaction conflict in ledger process

**Comment by pwc5232759** [comment]
#444 #446 #447 postponed to next week
