### ISSUE TITLE
Flag of Sync when node start

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/go-qlc#457]
### Description of the issue
 
Add a flag of sync when node start to run

### Issue-Type
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

### Checklist
- [ ] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS
* Go version
* Release tag/commit of the code

### Expected behavior
What should happen?

### Actual behavior
What is actually happening?

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by pwc5232759** [comment]
already done
