### ISSUE TITLE
Identify and resolve the fork in open block 

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/go-qlc#458]
### Description of the issue

The fork happened when the node is not sync yet

Need to identify this fork and resolve it.

_Please put an `x` against the checkboxes._  

### Issue-Type
- [ ] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [ ] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS
* Go version
* Release tag/commit of the code

### Expected behavior
What should happen?

### Actual behavior
What is actually happening?

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by zengchen221** [comment]
done
