### ISSUE TITLE
Consensus State sync between nodes when huge transactions are going on

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/go-qlc#664]
### Description of the issue
Consensus State sync issue between nodes when massive transactions are going on

### Issue-Type
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Detail info
node1: 
{
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "count": 621158,
    "unchecked": 3993
  }
}

node2:
{
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "count": 434171,
    "unchecked": 190883
  }
}

**Comment by wenchao-peng** [comment]
done
