### ISSUE TITLE
pre-research Account Chain hardfork solution

### ISSUE THREAD

**Issue by gythialy** [qlcchain/go-qlc#686]
### Description of the issue

- base on PoV
  - PoV and Account Chain dependencies
  - Impact on synchronization
- Independent of the PoV
- the PoV hardfork solution

The output document should contains the sequence diagram

### Issue-Type
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

**Comment by wenchaopeng** [comment]
done
