### ISSUE TITLE
minble-winble on QLCChain proposal

### ISSUE THREAD

**Issue by gythialy** [qlcchain/go-qlc#786]
### Issue-Type
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

**Comment by gythialy** [comment]
other privacy features have covered this feature

**Comment by ioannistsil** [comment]
@gythialy  what do u mean by that , can u be mo specific

**Comment by gythialy** [comment]
minble-winble is not suitable for us, we will develop our own privacy features.

**Comment by ioannistsil** [comment]
sounds promising , looking forward for more news about qlc privacy features
