### ISSUE TITLE
Week #52 Goals

### ISSUE THREAD

**Issue by zengchen221** [qlcchain/go-qlc#844]
Preparing to launch the Pov mainnet @gythialy @ariesunny @zengchen221 @wenchaopeng @wenyuangui @lc3091 

VM @gythialy 
#784 pre-research refine VM and post proposal
Ledger @zengchen221 
#798 implement cache and sqlite index interface
Performance @wenchaopeng 
#842 analysis node memory footprint
#830 statistical transaction confirmation time spent in each module
POW @wenyuangui 
#841 adjust pov algorithm efficiency
API @lc3091 
#840 Public key distribution API implementation
Wallet&Power @ariesunny

**Comment by ioannistsil** [comment]
hello, when POV mainet will be ready to use

**Comment by zengchen221** [comment]
@ioannistsil  thank you for your attention，next week will be ok !
