### ISSUE TITLE
[2020] Week #8 goals

### ISSUE THREAD

**Issue by zengchen221** [qlcchain/go-qlc#917]
settlement:
#913 implement settlement contract billing report @gythialy 
#915 add makefile and dockerfile for virtual-router @wenchaopeng 
#916 add testcase for virtual-router  @wenchaopeng

pov
#856  pov sync can not finished but sync queue is fulled  @wenyuangui 

privacy solution
#912 research and design QLC privacy solution @wenyuangui 

ledger
#904 add ledger unit test case and integrate testing @zengchen221 

api
#900 add rpc and vm unit test cases @lc3091 
#914 update the dpki API interfaces and the related documents @lc3091

**Comment by gythialy** [comment]
#904 postponed to next week
