### ISSUE TITLE
[2020] Week #12 goals

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/go-qlc#982]
Action is the foundational key to all success.

Settlement：
#978 refine generate multi-party invoice and summary reports interface @gythialy 
#979 implement asset registration @gythialy 
#985 follow up on cdr api issues @wenchaopeng 
#984 add pov builtin miner in gqlc @wenyuangui 

Privacy:
#980 implement permission control  @lc3091 
#990 add privacy base framework in gqlc @wenyuangui 
#991 pre-research orion for ptm solution @coolc4 

Chain：
#972 ledger iterator may not return value @zengchen221 
#960 add more test cases of ledger/API
qlcchain/qlc-test-bot#19 automatically create genesis account and genesis block for nodes

#986 increase UT coverage @wenchaopeng 
#987 add a robot to detect the status of airdrop account @wenchaopeng

**Comment by mtaro** [comment]
Next QLC to the moon
